services:
  collector:
    build:
      context: ../collector
    networks: 
        - internal
    ports:
        - "4317:4317"
        - "4318:4318"
    restart: unless-stopped

networks:
  internal:
    driver: bridge